# docker-compose.yml
version: '3.8'

services:
  # 1. Redis Service
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  # 2. Django Web Service
  web:
    build: .
    command: gunicorn personal_site.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./media:/app/media
      - ./db.sqlite3:/app/db.sqlite3  # <-- ADD THIS LINE
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis

  # 3. Celery Worker Service
  worker:
    build: .
    command: celery -A personal_site worker -l info
    volumes: # <-- ADD THIS SECTION
      - ./db.sqlite3:/app/db.sqlite3  # <-- ADD THIS LINE
    env_file:
      - .env
    depends_on:
      - redis